fix '400/linode busy' on rebuild
similar to this commit:
https://github.com/linode/linode-cli/commit/26a4801a5cd4713912656f5ff781c58e95d8a948

there was an extra boot command that was causing the 400 error.
pre-edit:

~/github/linode-cli -> linode-cli rebuild rebuild-test
Root Password:
Error: 400: Linode busy.;
~/github/linode-cli ->

post-edit:

~/github/linode-cli -> linode-cli rebuild rebuild-test
Root Password:
~/github/linode-cli ->